

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ColumnDefinition;
                ref class Grid;
                ref class ListView;
                ref class ScrollViewer;
                ref class StackPanel;
                ref class TextBlock;
                ref class Button;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}

namespace Labwork1UI
{
    partial ref class SplitPage : public ::Labwork1UI::Common::LayoutAwarePage, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ itemsViewSource;
        private: ::Windows::UI::Xaml::Controls::ColumnDefinition^ primaryColumn;
        private: ::Windows::UI::Xaml::Controls::Grid^ titlePanel;
        private: ::Windows::UI::Xaml::Controls::ListView^ itemListView;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ itemDetail;
        private: ::Windows::UI::Xaml::Controls::Grid^ itemDetailGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ itemDetailTitlePanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ itemTitle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ itemSubtitle;
        private: ::Windows::UI::Xaml::Controls::Button^ backButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pageTitle;
        private: ::Windows::UI::Xaml::VisualStateGroup^ ApplicationViewStates;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenLandscapeOrWide;
        private: ::Windows::UI::Xaml::VisualState^ FilledOrNarrow;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenPortrait;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenPortrait_Detail;
        private: ::Windows::UI::Xaml::VisualState^ Snapped;
        private: ::Windows::UI::Xaml::VisualState^ Snapped_Detail;
    };
}

