// <auto-generated />
namespace UniversityCodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDisciplineFactor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDisciplineFactor));
        
        string IMigrationMetadata.Id
        {
            get { return "201212092205286_AddDisciplineFactor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
