

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Button;
                ref class TextBox;
            }
        }
    }
}

namespace Labwork1
{
    partial ref class MainPage : public Windows::UI::Xaml::Controls::Page, 
        public Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: Windows::UI::Xaml::Controls::TextBlock^ ResultTextBlock;
        private: Windows::UI::Xaml::Controls::Button^ ResultButton1;
        private: Windows::UI::Xaml::Controls::Button^ ResultButton2;
        private: Windows::UI::Xaml::Controls::Button^ ResultButton3;
        private: Windows::UI::Xaml::Controls::Button^ ResultButton4;
        private: Windows::UI::Xaml::Controls::TextBox^ ResultTextBox1;
        private: Windows::UI::Xaml::Controls::Button^ ResultButton5;
    };
}

