

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "BasicPage.xaml.h"

using namespace Windows::Foundation;
using namespace Windows::UI::Xaml;
using namespace Windows::UI::Xaml::Controls;
using namespace Windows::UI::Xaml::Markup;
using namespace Labwork1UI;

void BasicPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///BasicPage.xaml
    Windows::UI::Xaml::Application::LoadComponent(this, ref new Windows::Foundation::Uri(L"ms-appx:///BasicPage.xaml"), Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the LayoutAwarePage named 'pageRoot'
    pageRoot = safe_cast<Labwork1UI::Common::LayoutAwarePage^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pageRoot"));
    // Get the Button named 'HuffmanEncodeButton'
    HuffmanEncodeButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanEncodeButton"));
    // Get the Button named 'HuffmanGenerateButton'
    HuffmanGenerateButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanGenerateButton"));
    // Get the Button named 'HuffmanDecodeButton'
    HuffmanDecodeButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanDecodeButton"));
    // Get the TextBox named 'HuffmanEncodeText'
    HuffmanEncodeText = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanEncodeText"));
    // Get the TextBox named 'HuffmanDecodeText'
    HuffmanDecodeText = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanDecodeText"));
    // Get the ListBox named 'HuffmanAlphabetListBox'
    HuffmanAlphabetListBox = safe_cast<Windows::UI::Xaml::Controls::ListBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanAlphabetListBox"));
    // Get the TextBox named 'HuffmanReadTextBox'
    HuffmanReadTextBox = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanReadTextBox"));
    // Get the Button named 'HuffmanReadButton'
    HuffmanReadButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanReadButton"));
    // Get the TextBox named 'HuffmanMapTextBox'
    HuffmanMapTextBox = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanMapTextBox"));
    // Get the Button named 'HuffmanMapButton'
    HuffmanMapButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HuffmanMapButton"));
    // Get the Button named 'ShannonFanoEncodeButton'
    ShannonFanoEncodeButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoEncodeButton"));
    // Get the Button named 'ShannonFanoGenerateButton'
    ShannonFanoGenerateButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoGenerateButton"));
    // Get the Button named 'ShannonFanoDecodeButton'
    ShannonFanoDecodeButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoDecodeButton"));
    // Get the TextBox named 'ShannonFanoEncodeText'
    ShannonFanoEncodeText = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoEncodeText"));
    // Get the TextBox named 'ShannonFanoDecodeText'
    ShannonFanoDecodeText = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoDecodeText"));
    // Get the ListBox named 'ShannonFanoAlphabetListBox'
    ShannonFanoAlphabetListBox = safe_cast<Windows::UI::Xaml::Controls::ListBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoAlphabetListBox"));
    // Get the TextBox named 'ShannonFanoReadTextBox'
    ShannonFanoReadTextBox = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoReadTextBox"));
    // Get the Button named 'ShannonFanoReadButton'
    ShannonFanoReadButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoReadButton"));
    // Get the TextBox named 'ShannonFanoMapTextBox'
    ShannonFanoMapTextBox = safe_cast<Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoMapTextBox"));
    // Get the Button named 'ShannonFanoMapButton'
    ShannonFanoMapButton = safe_cast<Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ShannonFanoMapButton"));
    // Get the TextBlock named 'pageTitle'
    pageTitle = safe_cast<Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pageTitle"));
    // Get the VisualStateGroup named 'ApplicationViewStates'
    ApplicationViewStates = safe_cast<Windows::UI::Xaml::VisualStateGroup^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ApplicationViewStates"));
    // Get the VisualState named 'FullScreenLandscape'
    FullScreenLandscape = safe_cast<Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenLandscape"));
    // Get the VisualState named 'Filled'
    Filled = safe_cast<Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Filled"));
    // Get the VisualState named 'FullScreenPortrait'
    FullScreenPortrait = safe_cast<Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenPortrait"));
    // Get the VisualState named 'Snapped'
    Snapped = safe_cast<Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Snapped"));
}

void BasicPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnHuffmanEncodeButtonClicked);
        break;
    case 2:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnHuffmanGenerateButtonClicked);
        break;
    case 3:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnHuffmanDecodeButtonClicked);
        break;
    case 4:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnHuffmanReadButtonClicked);
        break;
    case 5:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnHuffmanmapButtonClicked);
        break;
    case 6:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnShannonFanoEncodeButtonClicked);
        break;
    case 7:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnShannonFanoGenerateButtonClicked);
        break;
    case 8:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnShannonFanoDecodeButtonClicked);
        break;
    case 9:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnShannonFanoReadButtonClicked);
        break;
    case 10:
        (safe_cast<Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new Windows::UI::Xaml::RoutedEventHandler(this, (void (BasicPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&BasicPage::OnShannonFanoMapButtonClicked);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

